### ISSUE TITLE
I encountered a problem when i try to install this pakage.

### ISSUE THREAD

**Issue by matchseller** [unrolled/secure#63] opened 2019-11-26 10:22 UTC
This is the error report: verifying github.com/unrolled/secure@v1.0.5: github.com/unrolled/secure@v1.0.5: reading https://goproxy.io/sumdb/sum.golang.org/lookup/github.com/unrolled/secure@v1.0.5: 410 Gone

**Comment by unrolled** [comment] 2019-11-26 15:27
Hey, I'm not sure what the problem is or how to fix it. I found one related issue where they wanted go 1.13 in the go.mod file, which I did push up as v1.0.6... but that doesn't seem to help anything. Can you reach out to @goproxyio and see if they can help? I removed the proxy export line and the package download was successful.

**Comment by unrolled** [comment] 2020-01-03 14:37
Closing this for now. Let me know if this is still happening!

**Closed by unrolled** 2020-01-03 14:37 UTC
